name: QA Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests (Jest)
        run: npm test

      - name: Start API Server (Background)
        run: |
          node api/index.js &
          sleep 5

      - name: Run Cypress Tests
        run: npx cypress run


